name: matirx

on:
  push:

jobs:
  matrix-jobs:
    name: matrix jobs
    strategy:
      matrix:
        runner: [ubuntu-latest, windows-latest]
        python-version: [3.11, 3.12, 3.13]
        include:
          - runner: macos-latest
            python-version: 3.12
        exclude:
          - runner: windows-latest
            python-version: 3.13
    runs-on: ${{ matrix.runner }}
    steps:
      - runs: echo this job will runs on python version ${{ matrix.python-version }}  
   
